version: "3"
services:
  openwebrx:
    image: jketterl/openwebrx:stable
    volumes:
      - ./openwebrx/settings:/var/lib/openwebrx
    ports:
      - 8073:8073
    devices:
      - rtlsdrpath:rtlsdrpath
    tmpfs:
      - /tmp/openwebrx
    env_file:
      - .env